SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(FICHENO), SUM(TOTALPRICE), AVG(TOTALPRICE) 

FROM SALES WHERE CITY='ADANA'


SELECT MIN(TOTALPRICE), MAX(TOTALPRICE), COUNT(FICHENO), SUM(TOTALPRICE), AVG(TOTALPRICE) 

FROM SALES WHERE CITY='ÝSTANBUL'

